Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/BlockLength:
  Enabled: false