default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost  # Cambia "postgres" a "localhost"
  username: root
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mzaMeca

test:
  <<: *default
  database: myapi_test

production:
  adapter: postgresql
  encoding: unicode
  database: railway
  username: postgres
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['PGHOST'] %>
  port: <%= ENV['PGPORT'] %>