default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost  # Cambia "postgres" a "localhost"
  username: root
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mzaMeca

test:
  <<: *default
  database: myapi_test

production:
  <<: *default
  database: myapi_production
  username: myapi
  password: <%= ENV['MYAPI_DATABASE_PASSWORD'] %>
