default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DEV_DB_USERNAME'] %>
  password: <%= ENV['DEV_DB_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DEV_PGDATABASE'] %>
  host: <%= ENV['DEV_DB_HOST'] %>
  username: <%= ENV['DEV_DB_USERNAME'] %>
  password: <%= ENV['DEV_DB_PASSWORD'] %>

test:
  <<: *default
  database: myapi_test
  host: <%= ENV['DEV_DB_HOST'] || 'localhost' %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 2
  database: <%= ENV['PROD_PGDATABASE'] || 'railway' %>
  host: <%= ENV['RAILWAY_PRIVATE_DOMAIN'] || 'autorack.proxy.rlwy.net' %>
